<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRunner" project="Automation_Practice" tests="1" started="1" failures="0" errors="2" ignored="0">
  <testsuite name="StepDef.TestRunner" time="7.752" incomplete="true">
    <error>java.lang.RuntimeException: java.net.UnknownHostException: messages.cucumber.io&#13;
	at io.cucumber.core.plugin.MessageFormatter.writeMessage(MessageFormatter.java:36)&#13;
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)&#13;
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)&#13;
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:102)&#13;
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)&#13;
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:236)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
Caused by: java.net.UnknownHostException: messages.cucumber.io&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)&#13;
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)&#13;
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)&#13;
	at io.cucumber.core.plugin.UrlOutputStream.getResponseBody(UrlOutputStream.java:111)&#13;
	at io.cucumber.core.plugin.UrlOutputStream.sendRequest(UrlOutputStream.java:83)&#13;
	at io.cucumber.core.plugin.UrlOutputStream.close(UrlOutputStream.java:63)&#13;
	at sun.nio.cs.StreamEncoder.implClose(Unknown Source)&#13;
	at sun.nio.cs.StreamEncoder.close(Unknown Source)&#13;
	at java.io.OutputStreamWriter.close(Unknown Source)&#13;
	at io.cucumber.core.plugin.MessageFormatter.writeMessage(MessageFormatter.java:33)&#13;
	... 12 more&#13;
Caused by: java.net.UnknownHostException: messages.cucumber.io&#13;
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.PlainSocketImpl.connect(Unknown Source)&#13;
	at java.net.SocksSocketImpl.connect(Unknown Source)&#13;
	at java.net.Socket.connect(Unknown Source)&#13;
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)&#13;
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)&#13;
	at sun.net.NetworkClient.doConnect(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.openServer(Unknown Source)&#13;
	at sun.net.www.http.HttpClient.openServer(Unknown Source)&#13;
	at sun.net.www.protocol.https.HttpsClient.&lt;init&gt;(Unknown Source)&#13;
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)&#13;
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)&#13;
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)&#13;
	at sun.net.www.protocol.http.HttpURLConnection.getHeaderFields(Unknown Source)&#13;
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getHeaderFields(Unknown Source)&#13;
	at io.cucumber.core.plugin.UrlOutputStream.getResponseBody(UrlOutputStream.java:110)&#13;
	... 18 more&#13;
&#13;
</error>
    <testsuite name="Automation Practice Application User Story" time="7.752">
      <testcase name="1. User is able to Sign up in the application" classname="Automation Practice Application User Story" time="7.752">
        <error>org.openqa.selenium.WebDriverException: unknown error: net::ERR_INTERNET_DISCONNECTED
  (Session info: chrome=87.0.4280.141)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-K0TG6B2H', ip: '127.0.0.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 87.0.4280.141, chrome: {chromedriverVersion: 87.0.4280.88 (89e2380a3e36c..., userDataDir: C:\Users\srjbo\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:58083}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 3ddf2ecee50e75d70d8cdd2c7c92f86c&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)&#13;
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)&#13;
	at java.lang.reflect.Constructor.newInstance(Unknown Source)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)&#13;
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)&#13;
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)&#13;
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)&#13;
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)&#13;
	at StepDef.Step_Def.user_navigates_to_the_application_url(Step_Def.java:42)&#13;
	at âœ½.User navigates to the application url(classpath:features/Sign_Up.feature:6)&#13;
&#13;
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
